# Generated by Django 4.2.3 on 2023-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpcinfo',
            name='asset_responsible_person_id',
        ),
        migrations.RemoveField(
            model_name='pcinfo',
            name='asset_responsible_person_id',
        ),
        migrations.AddField(
            model_name='historicalpcinfo',
            name='asset_responsible_person_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcinfo',
            name='asset_responsible_person_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
