# Generated by Django 4.2.3 on 2023-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_remove_historicalpcinfo_asset_responsible_person_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessoryinfo',
            options={'verbose_name': '配件信息', 'verbose_name_plural': '配件信息'},
        ),
        migrations.AlterModelOptions(
            name='boardinfo',
            options={'verbose_name': '板卡信息', 'verbose_name_plural': '板卡信息'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门信息', 'verbose_name_plural': '部门信息'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccessoryinfo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 配件信息', 'verbose_name_plural': 'historical 配件信息'},
        ),
        migrations.AlterModelOptions(
            name='historicalboardinfo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 板卡信息', 'verbose_name_plural': 'historical 板卡信息'},
        ),
        migrations.AlterModelOptions(
            name='historicalosinfo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 系统信息', 'verbose_name_plural': 'historical 系统信息'},
        ),
        migrations.AlterModelOptions(
            name='historicalpcinfo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 机器信息', 'verbose_name_plural': 'historical 机器信息'},
        ),
        migrations.AlterModelOptions(
            name='historicalsummaryinfo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 汇总信息', 'verbose_name_plural': 'historical 汇总信息'},
        ),
        migrations.AlterModelOptions(
            name='osinfo',
            options={'verbose_name': '系统信息', 'verbose_name_plural': '系统信息'},
        ),
        migrations.AlterModelOptions(
            name='pcinfo',
            options={'verbose_name': '机器信息', 'verbose_name_plural': '机器信息'},
        ),
        migrations.AlterModelOptions(
            name='summaryinfo',
            options={'verbose_name': '汇总信息', 'verbose_name_plural': '汇总信息'},
        ),
        migrations.RemoveField(
            model_name='personnelinfo',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(to='cmdb.personnelinfo'),
        ),
        migrations.AlterField(
            model_name='historicalpcinfo',
            name='asset_responsible_person_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='资产责任人'),
        ),
        migrations.AlterField(
            model_name='pcinfo',
            name='asset_responsible_person_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='资产责任人'),
        ),
    ]
