# Generated by Django 4.2.3 on 2023-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_boardinfo_installed_time_boardinfo_maintain_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinfo',
            name='received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalboardinfo',
            name='received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
