# Generated by Django 4.2.3 on 2023-07-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_boardinfo_received_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinfo',
            name='installed_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardinfo',
            name='received_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalboardinfo',
            name='installed_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalboardinfo',
            name='received_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
