# Generated by Django 4.2.3 on 2023-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('build_url', models.URLField()),
                ('build_date', models.CharField(max_length=100)),
                ('build_file_name', models.CharField(max_length=100)),
                ('build_file_url', models.URLField()),
                ('local_download_path', models.CharField(max_length=200)),
            ],
        ),
    ]
