# Generated by Django 4.2.3 on 2023-07-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsbuild',
            name='build_date',
            field=models.CharField(max_length=100),
        ),
    ]
